version: '3.1'
services:
  humhub:
    image: mriedmann/humhub:1.6.2
    links:
      - "db:db"
    ports:
      - "8080:80"
    volumes:
      # - ./humhub-1.6.4/themes/trnbtl-theme:/var/www/localhost/htdocs/themes/HumHub
      - ./humhub-1.6.4:/var/www/localhost/htdocs
    environment:
      HUMHUB_DB_USER: humhub
      HUMHUB_DB_PASSWORD: humhub

  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: humhub
      MYSQL_USER: humhub
      MYSQL_PASSWORD: humhub

# volumes:
#   config: {}
#   uploads: {}
#   modules: {}
#   trnbtl-theme: {}